In [62]:
import pandas as pd
from pymongo import MongoClient
from pprint import pprint
from data.config import (mongo_name, mongo_pass)

In [63]:
client = MongoClient(f'mongodb://{mongo_name}:{mongo_pass}@ds249818.mlab.com:49818/heroku_6lctns1z')
db = client.heroku_6lctns1z
collection = db.sales_data
master_list = list(collection.find({}, {'_id': False}))

In [64]:
master_df = pd.DataFrame(master_list)

In [65]:
groupby_df = master_df.groupby(['Lines','Year','Month']).agg({'Sales revenue' : 'sum'})

In [66]:
groupby_df = groupby_df.reset_index()

In [139]:
# groupby_df.head(100)
# groupby_df.dtypes
test_df = groupby_df.loc[groupby_df['Lines'] == 'Trousers']
# test_df = groupby_df.loc[groupby_df['Sales revenue'] == 2183.4000000000005]
test_df.head(100)

        Lines  Year  Month  Sales revenue
364  Trousers  2014      1        11234.9
365  Trousers  2014      2         9908.5
366  Trousers  2014      3        12535.6
367  Trousers  2014      4        21354.8
368  Trousers  2014      5        15073.8
369  Trousers  2014      6         4895.4
370  Trousers  2014      7         7842.1
371  Trousers  2014      8         2576.9
372  Trousers  2014      9        85911.1
373  Trousers  2014     10        32250.5
374  Trousers  2014     11        11078.7
375  Trousers  2014     12         8924.5
376  Trousers  2015      1         5970.0
377  Trousers  2015      2        10029.8
378  Trousers  2015      3        18363.6
379  Trousers  2015      4        25400.5
380  Trousers  2015      5         9604.7
381  Trousers  2015      6         6614.9
382  Trousers  2015      7        12002.9
383  Trousers  2015      8         6332.0
384  Trousers  2015      9       205235.1
385  Trousers  2015     10        66875.6
386  Trousers  2015     11        18963.6
387  Trousers  2015     12        21904.5
388  Trousers  2016      1        33535.7
389  Trousers  2016      2        12222.5
390  Trousers  2016      3        14356.4
391  Trousers  2016      4        29409.8
392  Trousers  2016      5        34180.6
393  Trousers  2016      6        23928.1
394  Trousers  2016      7        19372.4
395  Trousers  2016      8        15749.2
396  Trousers  2016      9        35979.6
397  Trousers  2016     10        16640.8
398  Trousers  2016     11        20321.6
399  Trousers  2016     12        16739.6

In [140]:
years = {
    "2014" : {"x" : [1,2,3,4,5,6,7,8,9,10,11,12],"y" : [1,1,1,1,1,1,1,1,1,1,1,1], "mode" : "lines", "name" : "2014"},
    "2015" : {"x" : [1,2,3,4,5,6,7,8,9,10,11,12],"y" : [1,1,1,1,1,1,1,1,1,1,1,1], "mode" : "lines", "name" : "2015"},
    "2016" : {"x" : [1,2,3,4,5,6,7,8,9,10,11,12],"y" : [1,1,1,1,1,1,1,1,1,1,1,1], "mode" : "lines", "name" : "2016"},
}
lines = []
db_entry = []


for i in range(0,len(master_list)):
    new_line = master_list[i]['Lines']
    new_line = new_line.replace(" ", "_")
    if new_line not in lines:
        lines.append(new_line)

In [141]:
for line in lines:
    entry = {line : years}
    db_entry.append(entry)

In [142]:
pprint(db_entry[10])

{'Trousers': {'2014': {'mode': 'lines',
                       'name': '2014',
                       'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                       'y': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]},
              '2015': {'mode': 'lines',
                       'name': '2015',
                       'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                       'y': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]},
              '2016': {'mode': 'lines',
                       'name': '2016',
                       'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                       'y': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}}}

In [ ]:
sales_sum_dict = {}
for entry in db_entry:
    for key, value in entry.items():
        prod_line = key
        for x_key, x_value in value.items():
            year = int(x_key)
            sales_sum_dict[prod_line+str(year)] = []
            for c, value in enumerate(x_value["y"]):
                print(c, value)
                counter = c+1
                for index, row in groupby_df.iterrows():            
                        df_line = row[0].replace(" ", "_")
                        if df_line == prod_line and row[1] == int(year) and row[2] == counter:
                            x_value["y"][c] = row[3]
                            print("yup") 
                            print(value)
                if value == 1:
                    x_value["y"][c] = 0
                    print("nope")
                    print(value)

0 1
yup
1
nope
1
1 1
yup
1
nope
1
2 1
yup
1
nope
1
3 1
yup
1
nope
1
4 1
yup
1
nope
1
5 1
yup
1
nope
1
6 1
yup
1
nope
1
7 1
yup
1
nope
1
8 1
yup
1
nope
1
9 1
yup
1
nope
1
10 1
yup
1
nope
1
11 1
yup
1
nope
1
0 1
yup
1
nope
1
1 1
yup
1
nope
1
2 1
yup
1
nope
1
3 1
yup
1
nope
1
4 1
yup
1
nope
1
5 1
yup
1
nope
1
6 1
yup
1
nope
1
7 1
yup
1
nope
1
8 1
yup
1
nope
1
9 1
yup
1
nope
1
10 1
yup
1
nope
1
11 1
yup
1
nope
1
0 1
yup
1
nope
1
1 1
yup
1
nope
1
2 1
yup
1
nope
1
3 1
yup
1
nope
1
4 1
yup
1
nope
1
5 1
yup
1
nope
1
6 1
yup
1
nope
1
7 1
yup
1
nope
1
8 1
yup
1
nope
1
9 1
yup
1
nope
1
10 1
yup
1
nope
1
11 1
yup
1
nope
1
0 0
yup
0
1 0
yup
0
2 0
yup
0
3 0
yup
0
4 0
yup
0
5 0
yup
0
6 0
yup
0
7 0
yup
0
8 0
yup
0
9 0
yup
0
10 0
yup
0
11 0
yup
0
0 0
yup
0
1 0
yup
0
2 0
yup
0
3 0
yup
0
4 0
yup
0
5 0
yup
0
6 0
yup
0
7 0
yup
0
8 0
yup
0
9 0
yup
0
10 0
yup
0
11 0
yup
0
0 0
yup
0
1 0
yup
0
2 0
yup
0
3 0
yup
0
4 0
yup
0
5 0
yup
0
6 0
yup
0
7 0
yup
0
8 0
yup
0
9 0
yup
0
10 0
yup
0
11 0
yup
0
0 6186.200000000002
yup
6186.200000000002
1 2473.0
yup
2473.0
2 1190.9000000000003
yup
1190.9000000000003
3 1017.2
yup
1017.2
4 722.0999999999999
yup
722.0999999999999
5 154.8
yup
154.8
6 656.1
yup
656.1
7 426.1
yup
426.1
8 601.0
yup
601.0
9 16568.600000000002
yup
16568.600000000002
10 8657.0
yup
8657.0
11 10121.200000000003
yup
10121.200000000003
0 3777.0
yup
3777.0
1 518.0
yup
518.0
2 2096.0
yup
2096.0
3 3278.3999999999996
yup
3278.3999999999996
4 1271.6
yup
1271.6
5 657.1
yup
657.1
6 1239.0
yup
1239.0
7 781.0
yup
781.0
8 10604.2
yup
10604.2
9 34610.200000000004
yup
34610.200000000004
10 22388.8
yup
22388.8
11 21494.5
yup
21494.5
0 15699.0
yup
15699.0
1 2955.3
yup
2955.3
2 980.0
yup
980.0
3 198.0
yup
198.0
4 14281.9
yup
14281.9
5 40874.0
yup
40874.0
6 39946.7
yup
39946.7
7 26071.899999999998
yup
26071.899999999998
8 37371.6
yup
37371.6
9 13382.5
yup
13382.5
10 628.5
yup
628.5
11 3895.6
yup
3895.6
0 9095.5
yup
9095.5
1 4254.800000000001
yup
4254.800000000001
2 2914.1
yup
2914.1
3 1276.1000000000001
yup
1276.1000000000001
4 613.9
yup
613.9
5 248.3
yup
248.3
6 913.4000000000001
yup
913.4000000000001
7 394.9
yup
394.9
8 8440.599999999999
yup
8440.599999999999
9 10070.999999999998
yup
10070.999999999998

In [105]:
sales_sum_dict = {}
for index, row in groupby_df.iterrows():
    for entry in db_entry:
        for key, value in entry.items():
            prod_line = key
            for x_key, x_value in value.items():
                year = int(x_key)
                counter = 1
                sales_sum_dict[prod_line+str(year)] = []
                df_line = row[0].replace(" ", "_")
                for i in range(0, 12):
                    if df_line == prod_line and row[1] == int(year):
                        if row[2] == counter:
                            sales_sum_dict[prod_line+str(year)].append(row[3])
                            counter += 1
                        else:
                            sales_sum_dict[prod_line+str(year)].append(0)
                            counter += 1
pprint(sales_sum_dict)

{'Accessories2014': [],
 'Accessories2015': [],
 'Accessories2016': [],
 'City_Skirts2014': [],
 'City_Skirts2015': [],
 'City_Skirts2016': [],
 'City_Trousers2014': [],
 'City_Trousers2015': [],
 'City_Trousers2016': [],
 'Dresses2014': [],
 'Dresses2015': [],
 'Dresses2016': [],
 'Jackets2014': [],
 'Jackets2015': [],
 'Jackets2016': [],
 'Leather2014': [],
 'Leather2015': [],
 'Leather2016': [],
 'Outerwear2014': [],
 'Outerwear2015': [],
 'Outerwear2016': [],
 'Overcoats2014': [],
 'Overcoats2015': [],
 'Overcoats2016': [],
 'Shirt_Waist2014': [],
 'Shirt_Waist2015': [],
 'Shirt_Waist2016': [],
 'Sweat-T-Shirts2014': [],
 'Sweat-T-Shirts2015': [],
 'Sweat-T-Shirts2016': [],
 'Sweaters2014': [],
 'Sweaters2015': [],
 'Sweaters2016': [],
 'Trousers2014': [],
 'Trousers2015': [],
 'Trousers2016': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16739.6]}

In [48]:
pprint(len(sales_sum_dict["Accessories2014"]))

144

In [189]:
for entry in db_entry:
    for key, value in entry.items():
        prod_line = key
        for x_key, x_value in value.items():
            year = int(x_key)
            counter = 1
            sales_sum_list = x_value["y"]
            for key, value in sales_sum_dict.items():
#                 print((prod_line + str(year)))
#                 print(key)
                if key == (prod_line + str(year)):
                    x_value["y"] = value
            
pprint(db_entry)

[{'Accessories': {'2014': {'mode': 'lines',
                           'name': '2014',
                           'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                           'y': [2183.4000000000005,
                                 8280.5,
                                 30441.500000000004,
                                 25860.600000000002,
                                 63989.00000000001,
                                 71117.49999999999,
                                 100274.09999999999,
                                 33612.5,
                                 8640.499999999998,
                                 2728.8000000000006,
                                 2168.3,
                                 2718.8999999999996]},
                  '2015': {'mode': 'lines',
                           'name': '2015',
                           'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                           'y': [4622.799999999999,
                                 20181.899999999998,
                                 74320.59999999999,
                                 60752.80000000001,
                                 189139.39999999997,
                                 138186.0,
                                 239217.1,
                                 49553.1,
                                 10272.2,
                                 7950.6,
                                 5710.5,
                                 5544.0]},
                  '2016': {'mode': 'lines',
                           'name': '2016',
                           'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                           'y': [4413.0,
                                 2091.0,
                                 2337.5,
                                 669.1,
                                 2136.0,
                                 0.0,
                                 3064.0,
                                 1580.0,
                                 3725.4000000000005,
                                 4604.0,
                                 540.9,
                                 455.4]}}},
 {'City_Skirts': {'2014': {'mode': 'lines',
                           'name': '2014',
                           'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                           'y': [2183.4000000000005,
                                 8280.5,
                                 30441.500000000004,
                                 25860.600000000002,
                                 63989.00000000001,
                                 71117.49999999999,
                                 100274.09999999999,
                                 33612.5,
                                 8640.499999999998,
                                 2728.8000000000006,
                                 2168.3,
                                 2718.8999999999996]},
                  '2015': {'mode': 'lines',
                           'name': '2015',
                           'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                           'y': [4622.799999999999,
                                 20181.899999999998,
                                 74320.59999999999,
                                 60752.80000000001,
                                 189139.39999999997,
                                 138186.0,
                                 239217.1,
                                 49553.1,
                                 10272.2,
                                 7950.6,
                                 5710.5,
                                 5544.0]},
                  '2016': {'mode': 'lines',
                           'name': '2016',
                           'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                           'y': [4413.0,
                                 2091.0,
                                 2337.5,
                                 669.1,
                                 2136.0,
                                 0.0,
                                 3064.0,
                                 1580.0,
                                 3725.4000000000005,
                                 4604.0,
                                 540.9,
                                 455.4]}}},
 {'City_Trousers': {'2014': {'mode': 'lines',
                             'name': '2014',
                             'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                             'y': [2183.4000000000005,
                                   8280.5,
                                   30441.500000000004,
                                   25860.600000000002,
                                   63989.00000000001,
                                   71117.49999999999,
                                   100274.09999999999,
                                   33612.5,
                                   8640.499999999998,
                                   2728.8000000000006,
                                   2168.3,
                                   2718.8999999999996]},
                    '2015': {'mode': 'lines',
                             'name': '2015',
                             'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                             'y': [4622.799999999999,
                                   20181.899999999998,
                                   74320.59999999999,
                                   60752.80000000001,
                                   189139.39999999997,
                                   138186.0,
                                   239217.1,
                                   49553.1,
                                   10272.2,
                                   7950.6,
                                   5710.5,
                                   5544.0]},
                    '2016': {'mode': 'lines',
                             'name': '2016',
                             'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                             'y': [4413.0,
                                   2091.0,
                                   2337.5,
                                   669.1,
                                   2136.0,
                                   0.0,
                                   3064.0,
                                   1580.0,
                                   3725.4000000000005,
                                   4604.0,
                                   540.9,
                                   455.4]}}},
 {'Dresses': {'2014': {'mode': 'lines',
                       'name': '2014',
                       'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                       'y': [2183.4000000000005,
                             8280.5,
                             30441.500000000004,
                             25860.600000000002,
                             63989.00000000001,
                             71117.49999999999,
                             100274.09999999999,
                             33612.5,
                             8640.499999999998,
                             2728.8000000000006,
                             2168.3,
                             2718.8999999999996]},
              '2015': {'mode': 'lines',
                       'name': '2015',
                       'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                       'y': [4622.799999999999,
                             20181.899999999998,
                             74320.59999999999,
                             60752.80000000001,
                             189139.39999999997,
                             138186.0,
                             239217.1,
                             49553.1,
                             10272.2,
                             7950.6,
                             5710.5,
                             5544.0]},
              '2016': {'mode': 'lines',
                       'name': '2016',
                       'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                       'y': [4413.0,
                             2091.0,
                             2337.5,
                             669.1,
                             2136.0,
                             0.0,
                             3064.0,
                             1580.0,
                             3725.4000000000005,
                             4604.0,
                             540.9,
                             455.4]}}},
 {'Jackets': {'2014': {'mode': 'lines',
                       'name': '2014',
                       'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                       'y': [2183.4000000000005,
                             8280.5,
                             30441.500000000004,
                             25860.600000000002,
                             63989.00000000001,
                             71117.49999999999,
                             100274.09999999999,
                             33612.5,
                             8640.499999999998,
                             2728.8000000000006,
                             2168.3,
                             2718.8999999999996]},
              '2015': {'mode': 'lines',
                       'name': '2015',
                       'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                       'y': [4622.799999999999,
                             20181.899999999998,
                             74320.59999999999,
                             60752.80000000001,
                             189139.39999999997,
                             138186.0,
                             239217.1,
                             49553.1,
                             10272.2,
                             7950.6,
                             5710.5,
                             5544.0]},
              '2016': {'mode': 'lines',
                       'name': '2016',
                       'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                       'y': [4413.0,
                             2091.0,
                             2337.5,
                             669.1,
                             2136.0,
                             0.0,
                             3064.0,
                             1580.0,
                             3725.4000000000005,
                             4604.0,
                             540.9,
                             455.4]}}},
 {'Leather': {'2014': {'mode': 'lines',
                       'name': '2014',
                       'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                       'y': [2183.4000000000005,
                             8280.5,
                             30441.500000000004,
                             25860.600000000002,
                             63989.00000000001,
                             71117.49999999999,
                             100274.09999999999,
                             33612.5,
                             8640.499999999998,
                             2728.8000000000006,
                             2168.3,
                             2718.8999999999996]},
              '2015': {'mode': 'lines',
                       'name': '2015',
                       'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                       'y': [4622.799999999999,
                             20181.899999999998,
                             74320.59999999999,
                             60752.80000000001,
                             189139.39999999997,
                             138186.0,
                             239217.1,
                             49553.1,
                             10272.2,
                             7950.6,
                             5710.5,
                             5544.0]},
              '2016': {'mode': 'lines',
                       'name': '2016',
                       'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                       'y': [4413.0,
                             2091.0,
                             2337.5,
                             669.1,
                             2136.0,
                             0.0,
                             3064.0,
                             1580.0,
                             3725.4000000000005,
                             4604.0,
                             540.9,
                             455.4]}}},
 {'Overcoats': {'2014': {'mode': 'lines',
                         'name': '2014',
                         'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                         'y': [2183.4000000000005,
                               8280.5,
                               30441.500000000004,
                               25860.600000000002,
                               63989.00000000001,
                               71117.49999999999,
                               100274.09999999999,
                               33612.5,
                               8640.499999999998,
                               2728.8000000000006,
                               2168.3,
                               2718.8999999999996]},
                '2015': {'mode': 'lines',
                         'name': '2015',
                         'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                         'y': [4622.799999999999,
                               20181.899999999998,
                               74320.59999999999,
                               60752.80000000001,
                               189139.39999999997,
                               138186.0,
                               239217.1,
                               49553.1,
                               10272.2,
                               7950.6,
                               5710.5,
                               5544.0]},
                '2016': {'mode': 'lines',
                         'name': '2016',
                         'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                         'y': [4413.0,
                               2091.0,
                               2337.5,
                               669.1,
                               2136.0,
                               0.0,
                               3064.0,
                               1580.0,
                               3725.4000000000005,
                               4604.0,
                               540.9,
                               455.4]}}},
 {'Shirt_Waist': {'2014': {'mode': 'lines',
                           'name': '2014',
                           'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                           'y': [2183.4000000000005,
                                 8280.5,
                                 30441.500000000004,
                                 25860.600000000002,
                                 63989.00000000001,
                                 71117.49999999999,
                                 100274.09999999999,
                                 33612.5,
                                 8640.499999999998,
                                 2728.8000000000006,
                                 2168.3,
                                 2718.8999999999996]},
                  '2015': {'mode': 'lines',
                           'name': '2015',
                           'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                           'y': [4622.799999999999,
                                 20181.899999999998,
                                 74320.59999999999,
                                 60752.80000000001,
                                 189139.39999999997,
                                 138186.0,
                                 239217.1,
                                 49553.1,
                                 10272.2,
                                 7950.6,
                                 5710.5,
                                 5544.0]},
                  '2016': {'mode': 'lines',
                           'name': '2016',
                           'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                           'y': [4413.0,
                                 2091.0,
                                 2337.5,
                                 669.1,
                                 2136.0,
                                 0.0,
                                 3064.0,
                                 1580.0,
                                 3725.4000000000005,
                                 4604.0,
                                 540.9,
                                 455.4]}}},
 {'Sweaters': {'2014': {'mode': 'lines',
                        'name': '2014',
                        'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                        'y': [2183.4000000000005,
                              8280.5,
                              30441.500000000004,
                              25860.600000000002,
                              63989.00000000001,
                              71117.49999999999,
                              100274.09999999999,
                              33612.5,
                              8640.499999999998,
                              2728.8000000000006,
                              2168.3,
                              2718.8999999999996]},
               '2015': {'mode': 'lines',
                        'name': '2015',
                        'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                        'y': [4622.799999999999,
                              20181.899999999998,
                              74320.59999999999,
                              60752.80000000001,
                              189139.39999999997,
                              138186.0,
                              239217.1,
                              49553.1,
                              10272.2,
                              7950.6,
                              5710.5,
                              5544.0]},
               '2016': {'mode': 'lines',
                        'name': '2016',
                        'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                        'y': [4413.0,
                              2091.0,
                              2337.5,
                              669.1,
                              2136.0,
                              0.0,
                              3064.0,
                              1580.0,
                              3725.4000000000005,
                              4604.0,
                              540.9,
                              455.4]}}},
 {'Sweat-T-Shirts': {'2014': {'mode': 'lines',
                              'name': '2014',
                              'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                              'y': [2183.4000000000005,
                                    8280.5,
                                    30441.500000000004,
                                    25860.600000000002,
                                    63989.00000000001,
                                    71117.49999999999,
                                    100274.09999999999,
                                    33612.5,
                                    8640.499999999998,
                                    2728.8000000000006,
                                    2168.3,
                                    2718.8999999999996]},
                     '2015': {'mode': 'lines',
                              'name': '2015',
                              'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                              'y': [4622.799999999999,
                                    20181.899999999998,
                                    74320.59999999999,
                                    60752.80000000001,
                                    189139.39999999997,
                                    138186.0,
                                    239217.1,
                                    49553.1,

In [42]:
print(len(db_entry[1]['City_Skirts']["2014"]['y']))
print(len(db_entry[1]['City_Skirts']["2015"]['y']))
print(len(db_entry[1]['City_Skirts']["2016"]['y']))
print(db_entry[1]['City_Skirts']["2015"]['y'])

12
10
12
[1043015.0000000001, 3777.0, 206.7, 24581.5, 9154.0, 4622.799999999999, 1193.2, 66965.6, 175916.1, 5970.0]

In [41]:
print(len(db_entry[0]['Accessories']["2014"]['y']))
print(len(db_entry[0]['Accessories']["2015"]['y']))
print(len(db_entry[0]['Accessories']["2016"]['y']))
print(db_entry[0]['Accessories']["2015"]['y'])

12
10
12
[1043015.0000000001, 3777.0, 206.7, 24581.5, 9154.0, 4622.799999999999, 1193.2, 66965.6, 175916.1, 5970.0]

In [33]:
pprint(db_entry[0])

{'Accessories': {'2014': {'mode': 'lines',
                          'name': '2014',
                          'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                          'y': []},
                 '2015': {'mode': 'lines',
                          'name': '2015',
                          'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                          'y': []},
                 '2016': {'mode': 'lines',
                          'name': '2016',
                          'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                          'y': []}}}

In [193]:
# db.line_graph.insert_one(db_entry[0])